version: "3"
services:
  redis:
    image: redis:alpine
    ports:
      - "5000:6379"
  as:
    image: addition-server
    ports:
      - "8080:8080"
  webdis:
    image: anapsix/webdis
    ports:
      - "7379:7379"